# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
TOMsimilarity_parallel <- function(Adjacency_Matrix_Rcpp_NumericMatrix, nthreads) {
    .Call('_biomda_TOMsimilarity_parallel', PACKAGE = 'biomda', Adjacency_Matrix_Rcpp_NumericMatrix, nthreads)
}